[package]
name = "redon-tech/weather-systems"
version = "2.0.0-alpha.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
roact = "roblox/roact@1.4.4"
studiocomponents = "sircfenner/studiocomponents@0.1.1"