return {
	conditionData = {
		names = {
			[1] = "Settled Fine",
			[2] = "Fine Weather",
			[3] = "Fine Becoming Less Settled",
			[4] = "Fairly Fine Showery Later",
			[5] = "Showery Becoming more unsettled",
			[6] = "Unsettled, Rain later",
			[7] = "Rain at times, worse later.",
			[8] = "Rain at times, becoming very unsettled",
			[9] = "Very Unsettled, Rain",
			[10] = "Settled Fine",
			[11] = "Fine Weather",
			[12] = "Fine, Possibly showers",
			[13] = "Fairly Fine, Showers likely",
			[14] = "Showery Bright Intervals",
			[15] = "Changeable some rain",
			[16] = "Unsettled, rain at times",
			[17] = "Rain at Frequent Intervals",
			[18] = "Very Unsettled, Rain",
			[19] = "Stormy, much rain",
			[20] = "Settled Fine",
			[21] = "Fine Weather",
			[22] = "Becoming Fine",
			[23] = "Fairly Fine, Improving",
			[24] = "Fairly Fine, Possibly showers, early",
			[25] = "Showery Early, Improving",
			[26] = "Changeable Mending",
			[27] = "Rather Unsettled Clearing Later",
			[28] = "Unsettled, Probably Improving",
			[29] = "Unsettled, short fine Intervals",
			[30] = "Very Unsettled, Finer at times",
			[31] = "Stormy,possibly improving",
			[32] = "Stormy, much rain",
		},
	},
	pressure = {
		Pa = 0.01, -- Pascal to millibar
		kPa = 10, -- Kilopascal to millibar
		bar = 1000, -- Bar to millibar
		mbar = 1, -- Millibar to millibar
		psi = 68.9475729, -- Pound per Square Inch to millibar
		atm = 1013.25, -- Standard Atmosphere to millibar
	},
	months = {
		{
			Name = "January",
			Short = "Jan",
			MinDays = 0,
			MaxDays = 31,
		},
		{
			Name = "February",
			Short = "Feb",
			MinDays = 31,
			MaxDays = 59,
		},
		{
			Name = "March",
			Short = "Mar",
			MinDays = 59,
			MaxDays = 90,
		},
		{
			Name = "April",
			Short = "Apr",
			MinDays = 90,
			MaxDays = 120,
		},
		{
			Name = "May",
			Short = "May",
			MinDays = 120,
			MaxDays = 151,
		},
		{
			Name = "June",
			Short = "Jun",
			MinDays = 151,
			MaxDays = 181,
		},
		{
			Name = "July",
			Short = "Jul",
			MinDays = 181,
			MaxDays = 212,
		},
		{
			Name = "August",
			Short = "Aug",
			MinDays = 212,
			MaxDays = 243,
		},
		{
			Name = "September",
			Short = "Sep",
			MinDays = 243,
			MaxDays = 273,
		},
		{
			Name = "October",
			Short = "Oct",
			MinDays = 273,
			MaxDays = 304,
		},
		{
			Name = "November",
			Short = "Nov",
			MinDays = 304,
			MaxDays = 334,
		},
		{
			Name = "December",
			Short = "Dec",
			MinDays = 334,
			MaxDays = 365,
		},
	},
}
